In [ ]:
""" Created on August 22, 2025 // Updated on March 20, 2026 // @author: Sarah Shi """

import os
import numpy as np
import pandas as pd

import mineralML as mm

import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# Helper Functions Quickstart

This notebook demonstrates how to use helper functions defined in mineralML:
1. Load a CSV with `load_df` (or `pd.read_csv` directly).
2. Clean and align columns with `prep_df`.
3. Convert between oxide and elemental wt% with `oxide_to_element` / `element_to_oxide`

We loaded in the ``mineralML`` Python package as ``mm``. ``mineralML`` has trained machine learning models for classifying minerals. This implementation aims to get your electron microprobe or quantitative EDS compositions classified and processed. We remove some degrees of freedom to simplify the process as much as possible. The minerals considered for this study include: Amphibole, Apatite, Biotite, Calcite, Chlorite, Epidote, Feldspar (KFeldspar and Plagioclase), Garnet, Glass, Kalsilite, Leucite, Melilite, Muscovite, Nepheline, Olivine, Pyroxene (Clinopyroxene and Orthopyroxene), Quartz, Rhombohedral_Oxides (Hematite-Ilmenite), Rutile, Serpentine, Spinels (Magnetite-Spinel), Titanite, Tourmaline, and Zircon. 

One CSV file containing your electron microprobe analyses in oxide weight percentages is necessary. Find an example [here](https://github.com/sarahshi/mineralML/blob/main/docs/examples/training_hundred.csv). The necessary oxides are $SiO_2$, $TiO_2$, $Al_2O_3$, $FeO_t$, $MnO$, $MgO$, $CaO$, $Na_2O$, $K_2O$, $Cr_2O_3$, and $P_2O_5$. For the oxides not analyzed for specific minerals, the preprocessing will fill in the nan values as 0.

## 1. Load and prepare data for analysis

In [2]:
# Read in your dataframe of mineral data, called training_hundred.csv. 

df_load = mm.load_df('training_hundred.csv')
display(df_load.head())

,Sample Name,SiO2,TiO2,Al2O3,FeOt,MnO,MgO,CaO,Na2O,K2O,P2O5,Cr2O3,Mineral
0,Z2099,42.960,1.800,14.330,4.070,0.070,17.390,12.030,3.100,0.030,NaN,0.65,Amphibole
2110,UC787-1c-hb,45.862,1.228,5.721,20.418,0.696,10.888,10.114,1.759,NaN,NaN,NaN,Amphibole
2111,UC787-1r-hb,46.040,1.355,5.633,21.778,0.776,9.714,9.779,1.737,NaN,NaN,NaN,Amphibole
2112,UC199-1c-hb,46.937,1.174,5.496,17.753,0.695,12.280,10.546,1.350,0.463,NaN,NaN,Amphibole
2113,UC199-2c-hb,46.313,1.232,5.743,17.504,0.655,11.785,10.611,1.320,0.492,NaN,NaN,Amphibole

## 2. Clean and align columns of dataframe

In [ ]:
# Prepare the dataframe by removing rows with too many NaNs, and filling in zeros. 

df_nn = mm.prep_df(df_load,
                   convert_fe=False, # optionally convert disparate input formats of Fe all to FeOt
                   drop_empty_rows=False, # optionally drop rows with more nan values than the min_oxide_count
                   min_oxide_count=2, # minimum number of oxides in a row to keep that analysis
                   verbose=True
                   )
display(df_nn.head())

/var/folders/k_/fnnxsv2n52qb5r1hq85f3p2c0000gn/T/ipykernel_27078/3623079433.py:3: UserWarning: The column 'ZrO2' was missing and has been filled with NaN.
  df_nn = mm.prep_df_nn(df_load)
/var/folders/k_/fnnxsv2n52qb5r1hq85f3p2c0000gn/T/ipykernel_27078/3623079433.py:3: UserWarning: Some non-numeric values were found in the oxides columns and have been coerced to NaN.
  df_nn = mm.prep_df_nn(df_load)

,Sample Name,SiO2,TiO2,Al2O3,FeOt,MnO,MgO,CaO,Na2O,K2O,P2O5,Cr2O3,Mineral,ZrO2
0,Z2099,42.960,1.800,14.330,4.070,0.070,17.390,12.030,3.100,0.030,0.0,0.65,Amphibole,0.0
1,UC787-1c-hb,45.862,1.228,5.721,20.418,0.696,10.888,10.114,1.759,0.000,0.0,0.00,Amphibole,0.0
2,UC787-1r-hb,46.040,1.355,5.633,21.778,0.776,9.714,9.779,1.737,0.000,0.0,0.00,Amphibole,0.0
3,UC199-1c-hb,46.937,1.174,5.496,17.753,0.695,12.280,10.546,1.350,0.463,0.0,0.00,Amphibole,0.0
4,UC199-2c-hb,46.313,1.232,5.743,17.504,0.655,11.785,10.611,1.320,0.492,0.0,0.00,Amphibole,0.0

## 3. Convert between oxide and elemental wt%

These may be generally useful functions for converting between oxide and elemental data.

In [4]:
df_nn_elemental, factors_ox2el = mm.oxide_to_element(df_nn)
display(df_nn_elemental)
display(factors_ox2el)

,Si,Ti,Al,Fe,Mn,Mg,Ca,Na,K,P,Cr,Zr
0,20.081004,1.078815,7.584172,3.163648,0.054212,10.486794,8.597730,2.299683,0.024904,0.0,0.444732,0.0
1,21.437500,0.735991,3.027847,15.871099,0.539022,6.565855,7.228382,1.304884,0.000000,0.0,0.000000,0.0
2,21.520704,0.812108,2.981273,16.928239,0.600979,5.857891,6.988961,1.288564,0.000000,0.0,0.000000,0.0
3,21.939993,0.703627,2.908766,13.799570,0.538248,7.405281,7.537129,1.001475,0.384358,0.0,0.000000,0.0
4,21.648313,0.738389,3.039491,13.606020,0.507270,7.106778,7.583584,0.979220,0.408433,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2795,15.177387,0.000000,0.000000,0.005988,0.000000,0.002606,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2796,15.216393,0.000000,0.000000,0.006049,0.000000,0.002632,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2797,15.094715,0.000000,0.000000,0.006013,0.000000,0.002617,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2798,14.855491,0.000000,0.000000,0.005985,0.000000,0.002604,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2799,15.238246,0.000000,0.000000,0.005951,0.000000,0.002590,0.000000,0.000000,0.000000,0.0,0.000000,0.0

SiO2     0.467435
TiO2     0.599341
Al2O3    0.529251
FeOt     0.777309
MnO      0.774457
MgO      0.603036
CaO      0.714691
Na2O     0.741833
K2O      0.830148
P2O5     0.436426
Cr2O3    0.684203
ZrO2     0.740346
dtype: float64

In [5]:
df_nn_oxide, factors_el2ox = mm.element_to_oxide(df_nn_elemental)
display(df_nn_oxide)
display(factors_el2ox)

,SiO2,TiO2,Al2O3,FeOt,MnO,MgO,CaO,Na2O,K2O,P2O5,Cr2O3,ZrO2
0,42.960000,1.800,14.330,4.070000,0.070,17.390000,12.030,3.100,0.030,0.0,0.65,0.0
1,45.862000,1.228,5.721,20.418000,0.696,10.888000,10.114,1.759,0.000,0.0,0.00,0.0
2,46.040000,1.355,5.633,21.778000,0.776,9.714000,9.779,1.737,0.000,0.0,0.00,0.0
3,46.937000,1.174,5.496,17.753000,0.695,12.280000,10.546,1.350,0.463,0.0,0.00,0.0
4,46.313000,1.232,5.743,17.504000,0.655,11.785000,10.611,1.320,0.492,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2795,32.469518,0.000,0.000,0.007704,0.000,0.004321,0.000,0.000,0.000,0.0,0.00,0.0
2796,32.552966,0.000,0.000,0.007781,0.000,0.004365,0.000,0.000,0.000,0.0,0.00,0.0
2797,32.292657,0.000,0.000,0.007736,0.000,0.004340,0.000,0.000,0.000,0.0,0.00,0.0
2798,31.780875,0.000,0.000,0.007699,0.000,0.004319,0.000,0.000,0.000,0.0,0.00,0.0
2799,32.599717,0.000,0.000,0.007655,0.000,0.004294,0.000,0.000,0.000,0.0,0.00,0.0

SiO2     2.139335
TiO2     1.668498
Al2O3    1.889461
FeOt     1.286489
MnO      1.291226
MgO      1.658276
CaO      1.399207
Na2O     1.348012
K2O      1.204605
P2O5     2.291341
Cr2O3    1.461555
ZrO2     1.350719
dtype: float64

Compare the `df_nn_oxide` and `df_nn` dataframes. Are these data the same?